name: Update README2

on:
  schedule:
    - cron: '* */12 * * *' # Every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README
    
    steps:
      - uses: actions/checkout@v2.3.4
      
      - name: Set up recent activity configuration
        run: echo "recent-activity:\n  - 'ðŸ“” Created new repository [fjalaf/jalaf.github.io](https://github.com/fjalaf/jalaf.github.io)'\n  - 'â¬†ï¸ Pushed 1 commit(s) to [fjalaf/fjalaf](https://github.com/fjalaf/fjalaf)'" > .github/recent-activity.config.yml

      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
